site_name: Lame
site_description: A language for making lame games

repo_name: bweir/lame
repo_url: https://github.com/bweir/lame

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  icon:
    logo: fontawesome/solid/gamepad
  features:
    # - navigation.instant
    - navigation.tabs

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bweir/lame

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
  - Language:
      - Types: types.md
      - Blocks: blocks.md
      - Operators: operators.md
      - Keywords: keywords.md
      - Whitespace: whitespace.md
      - Comments: comments.md
  - Development:
      - Features: features.md
