---
name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dist:
          - "darwin/amd64"
          - "darwin/arm64"
          - "linux/386"
          - "linux/amd64"
          - "linux/arm"
          - "linux/386"
          - "linux/amd64"
          - "linux/arm"
        go: ["1.15"]
    name: "${{ matrix.dist }}"
    steps:
      - uses: actions/checkout@v2

      - run:
          echo "::set-env name=GOOS::$(dirname ${{ matrix.dist }})"
          echo "::set-env name=GOARCH::$(basename ${{ matrix.dist }})"
          echo "::set-env name=COMMIT::$(echo "$GITHUB_SHA" | cut -c -8)"
          echo "::set-env name=BRANCH::$(basename "$GITHUB_REF")"

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - env:
          CGO_ENABLED: "0"
        run: |
          go build .
          zip -9 lame-${BRANCH}-${COMMIT}-${GOOS}-${GOARCH}.zip lame{,.exe}

      - uses: actions/upload-artifact@v2
        with:
          name: "lame-${REF}-${GOOS}-${GOARCH}"
          path: "*.zip"
