---
name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dist:
          - "darwin/amd64"
          - "linux/386"
          - "linux/amd64"
          - "linux/arm"
          - "windows/386"
          - "windows/amd64"
        go: ["1.15"]
    name: "${{ matrix.dist }}"
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "GOOS=$(dirname ${{ matrix.dist }})" >> $GITHUB_ENV
          echo "GOARCH=$(basename ${{ matrix.dist }})" >> $GITHUB_ENV
          echo "REF=$(basename "$GITHUB_REF")" >> $GITHUB_ENV

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - env:
          CGO_ENABLED: "0"
        run: |
          go build .
          zip -9 lame-${{ env.REF }}-${{ env.GOOS }}-${{ env.GOARCH }}.zip lame{,.exe}

      - uses: actions/upload-artifact@v2
        with:
          name: "lame-${{ env.REF }}-${{ env.GOOS }}-${{ env.GOARCH }}"
          path: "*.zip"
