---
name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dist:
          - "darwin/amd64"
          - "darwin/arm64"
          - "linux/386"
          - "linux/amd64"
          - "linux/arm"
          - "linux/386"
          - "linux/amd64"
          - "linux/arm"
        go: ["1.15"]
    name: "${{ matrix.dist }}"
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "GOOS=$(dirname ${{ matrix.dist }})" >> $GITHUB_ENV
          echo "GOARCH=$(basename ${{ matrix.dist }})" >> $GITHUB_ENV
          echo "COMMIT=$(echo "$GITHUB_SHA" | cut -c -8)" >> $GITHUB_ENV
          echo "BRANCH=$(basename "$GITHUB_REF")" >> $GITHUB_ENV

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - env:
          CGO_ENABLED: "0"
        run: |
          go build .
          zip -9 lame-${BRANCH}-${COMMIT}-${GOOS}-${GOARCH}.zip lame{,.exe}

      - uses: actions/upload-artifact@v2
        with:
          name: "lame-${REF}-${GOOS}-${GOARCH}"
          path: "*.zip"
